ru = {"&File": 'Файл',
      "&View": 'Вид',
      "New": 'Новый',
      "Open": 'Открыть',
      "Save": 'Сохранить',
      "Save As": 'Сохранить как',
      "Exit": 'Выход',
      "Style": 'Стиль',
      "Dark": 'Dark',
      "Light": 'Light',
      "Lang": 'Язык',
      "RU": 'RU',
      "EN": 'EN',
      "Enable/Disable File browser": 'Вкл/Выкл файл-браузер',
      "About": 'О программе'}

en = {"&File": 'File',
      "&View": 'View',
      "New": 'New',
      "Open": 'Open',
      "Save": 'Save',
      "Save As": 'Save As',
      "Exit": 'Exit',
      "Style": 'Style',
      "Dark": 'Dark',
      "Light": 'Light',
      "Lang": 'Lang',
      "RU": 'RU',
      "EN": 'EN',
      "Enable/Disable File browser": 'Enable/Disable File browser',
      "About": 'About'}
